site_name: LCEXOPLANET Docs
site_url: "https://diegohs79.github.io/lcexoplanet//"
nav:
  - Home: index.md
  # - Howtos:
  #     - "Config File": howtos/config_file.md
  #     - "Running a task": "howtos/running_tasks.md"
  #     - Flows: howtos/flows.md
  # - Tutorials: tutorials/adding_source.md
  - References:
      - "SQL Sources": references/utilities.md
      # - "API Sources": references/api_sources.md
      # - "Flows library": references/flows_library.md
  # - Task library: references/task_library.md

theme:
  name: "material"
  features:
    - navigation.tabs
plugins:
  - search
  - mkdocstrings:
      watch:
        - lcexoplanet
      handlers:
        python:
          rendering:
            show_root_heading: yes
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
dev_addr: "0.0.0.0:8000"
