[tool.poetry]
name = "lcexoplanet"
version = "0.1.0"
description = ""
authors = ["DiegoHS79 <diego.hidalgo@hotmail.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
